dist: trusty  # For python 2.6
language: python
matrix:
    include:
        - python: "2.6"
          env: TOXENV=py26
        - python: "2.7"
          env: TOXENV=py27
        - python: "3.4"
          env: TOXENV=py34
        - python: "3.5"
          env: TOXENV=py35
        - python: "3.6"
          env: TOXENV=py36
        - python: "3.7"
          env: TOXENV=py37
          sudo: required
          dist: xenial
        - python: "2.7"
          env: TOXENV=docs
install:
    - pip install tox
script:
    - tox
notifications:
  irc:
    channels:
      - "irc.mozilla.org#payments"
    on_success: change
    on_failure: always
